### ISSUE TITLE
[AVM Module Issue]: problem with provider pinning for `azure/azapi`

### ISSUE THREAD

**Issue by JensKruseAvanade** [Azure/terraform-azurerm-avm-ptn-policyassignment#65] opened 2024-12-05 17:49 UTC
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

2.1

### Description

`Terraform init`

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider azure/azapi:
│ no available releases match the given constraints >= 1.14.0, ~> 1.14, ~>
│ 2.0, < 3.0.0
```

My assumption is, that there is a typo in the provider requirements for "Azure/azapi" (instead of "azure/azapi" (see terraform-azurerm-avm-ptn-policyassignment/terraform.tf, line 5).

**Comment by JensKruseAvanade** [comment] 2024-12-11 08:50
@bjornhofer Sorry to bother you: any update on this? How can I support?

**Comment by bjornhofer** [comment] 2024-12-11 16:57
@JensKruseAvanade Hi, no problem I'm currently a bit in a rush with other things - but I plan to solve it at latest on the upcoming Friday.

**Comment by bjornhofer** [comment] 2024-12-12 15:24
Hello @JensKruseAvanade 

I could not reproduce your issue in my test environment. (see: [https://ibb.co/YBXwqRr](screenshot)

Can you provide me more details (Terraform version, operating system, ...)


Thanks in advance

Björn

**Comment by JensKruseAvanade** [comment] 2024-12-12 16:31
Hi @bjornhofer 
Thanks for your answer.
This is my github action environment:
```yml
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
[...]
      # Install the preferred version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9
```
HTH,
Jens

**Comment by JensKruseAvanade** [comment] 2024-12-12 17:30
Just ran a `terraform providers` with the pipeline.

Providers required by other AVM modules (showing here just 'azure/azapi':
```
...
├── module.storage_account
...
│   ├── provider[registry.terraform.io/azure/azapi] >= 1.14.0, < 3.0.0
...
├── module.log_analytics_workspace
│   ├── provider[registry.terraform.io/azure/azapi] ~> 2.0
...
```

With that, no problems occur, so I agree that this issue is not about the spelling of the providers. Could it be something about versioning requirements? Found this one here ... https://stackoverflow.com/questions/76272116/terraform-resolve-no-available-releases-match-the-given-constraints-error

**Comment by steph409** [comment] 2024-12-13 15:58
Hi @JensKruseAvanade,

the problem is that you have two version requirements (one coming from the module, and one coming from somewhere in your code), so it doesn't find a version. Right now, the module is soft-pinned on azapi version 1.14 [here](https://github.com/Azure/terraform-azurerm-avm-ptn-policyassignment/blob/main/terraform.tf#L6). Somewhere in your code, you are requiring azapi to be version to be `~> 2.0, < 3.0.0`. This can either be if you specify it directly or you are calling modules that do. Can you try to deploy this separately, or to soften the version constraint?

@bjornhofer - it would be great if our code would also work with azapi version 2, but we should test it before removing the constraint.

**Comment by bjornhofer** [comment] 2024-12-19 12:46
Hello @JensKruseAvanade so far all changes are merged to main. Please let me know if it fixed your issue, so I can close the issue.

**Comment by bjornhofer** [comment] 2024-12-20 08:18
@JensKruseAvanade sorry, I've missed the step of releasing the new version (my first time with AVM modules).
It has been released now - please update your provider ( `terraform init --upgrade `) to the latest version and it should now work.

**Closed by bjornhofer** 2024-12-20 08:18 UTC
Labels: Type: Bug :bug:, Language: Terraform :globe_with_meridians:

**Comment by JensKruseAvanade** [comment] 2024-12-20 14:16
Solved this issue: there had been special characters in the `name` of the policy assignment. After removing them, all went fine!
